### ISSUE TITLE
Table copied from Win32 PPT is having double spaced between lines.

### ISSUE THREAD

**Issue by zepei-sun** [microsoft/roosterjs#1003]
**Describe the bug**
If you copy a table from Win32 PPT app, the space between lines are doubled

**To Reproduce**
1. Go to https://microsoft-my.sharepoint-df.com/:p:/p/zesu/Eb9scKmMgGBDrQesJtwKHJcBSJO31fkUV_da94cxYBcm-g?e=DOAdpz
2. Open in Win 32 PPT
3. Copy the table to rooster editor

**Expected behavior**
Display the table the same as PPT does

**Screenshots**
![image](https://user-images.githubusercontent.com/101152963/170554570-8176b657-693d-4f76-841c-f6b5bdc0d904.png)

**Comment by JiuqingSong** [comment]
I found that this is a layout issue rather than a pasting issue. Here's a mini repro:

```html
<!doctype html>

<html><body>
<div style="font-size: 18pt; width: 100px"><span style="font-size:8pt">test test test test test test test test test </span></div>
</body></html>
```

With this code, it can repro the same issue. But if remove the line `<!doctype html>`, this issue is gone. Unfortunately, PowerPoint generated such kind of HTML which doesn't layout correctly with `<!doctype html>`.
