### ISSUE TITLE
how to modify enter tag with p？

### ISSUE THREAD

**Issue by HereSinceres** [Microsoft/roosterjs#103]
**Describe the bug**
Why is enter tag div instead of P?
**To Reproduce**

**Expected behavior**
enter tag is p

**Screenshots**

**Device Information**
all

**Additional context**
how to modify enter tag with p？

**Comment by JiuqingSong** [comment]
<P> tag has a built-in 16px margin top and bottom, so that we always need some CSS rules to remove these margins, that's why we use DIV as default line tag here.

But if you want, you can try using <p></p> as initial content so that new lines will be <P> added by browser.

**Comment by AlphaGeek** [comment]
Similar issue, my document has areas where the user can enter defined as <p> tags, so they enter content in these <p> tags, however when typing in these <p> tags and hitting Enter, it creates a new element rather than just wrapping the text in a new line, so if you hit enter 10 times you have each line of text in a new element (so 10 elements in this case).   Is there a way to have the Enter key just create a new line in the existing element?
