### ISSUE TITLE
Auto-formatting of numbered lists

### ISSUE THREAD

**Issue by EpokK** [microsoft/roosterjs#1129]
**Describe the bug**
Auto-formatting for numbered lists is not correct.

**To Reproduce**
1. In a new line, type `4)` then click `space`

**Current behavior**
- Issue 1: The number 4, or any number for that matter, will become 1
- Issue 2: the closing parenthesis will become a dot. So from "4)" we now have "1."
- Issue 3: If you click on the order list button to turn it off, the number you wrote is also deleted

**Expected behavior**
Do not change the numbers and symbols when we auto-format. A `4` should remain a `4.`
`A )` should remain `a )`.
So even if we create a numbered list automatically, we should keep the data as entered by the user if possible.

**Comment by JiuqingSong** [comment]
Thanks.
1 is known as a bug.
For 2, we have already supported list such as `(A)`, `(a)` or `a)`, (need to enable ExperimentalFeature `AutoFormatList`. However, there seems still bug to support `(1)`, `1)`. I feel they should also be supported @jvillalobos @juliaroldi 
For 3, this is currently by design. The number is not part of the content so they will be removed when turn of list. @jvillalobos what do you think?

**Comment by jvillalobos** [comment]
Yes, both examples in 2 should be supported. For 3, I agree that it's by design, and should probably stay that way. If you're on an ordered list and click on the button, the list number/letter should go away, and I don't think it should matter how it was created. If you want to undo the auto-formatting, then the Undo action should be the right way to go back.

**Comment by juliaroldi** [comment]
Covered by the AutoFormatList experimental feature.
