### ISSUE TITLE
Cannot read properties null when use createContextMenuPlugin()

### ISSUE THREAD

**Issue by BDMChau** [microsoft/roosterjs#1163]
I'm using createContextMenuPlugin(), createTableEditMenuProvider(), createImageEditMenuProvider()  to use Right Click for expanding the menu options like image below.

![Screenshot from 2022-08-09 11-51-13](https://user-images.githubusercontent.com/64347888/183567064-8a90ccb2-becf-4004-bd62-7e98b09b302b.png)

But I always have this error in console when Right Click
![Screenshot from 2022-08-09 11-52-25](https://user-images.githubusercontent.com/64347888/183567194-a1b4daf5-08a8-46e1-9a2b-610fcacf5542.png)

I'm using Editor from 'roosterjs-editor-core' to create custom Editor

**Comment by JiuqingSong** [comment]
Please provide more info such as your source code, or a link to a live project such as codepen so that we can check.

**Comment by BDMChau** [comment]
Here is our demo code.
https://github.com/BDMChau/test-roosterjs

**Comment by JiuqingSong** [comment]
I've tried with your code and it turns out the `<Rooster />` component is not used in your code so that a required property uiUtilities is not initialized in the plugin. You can see https://github.com/microsoft/roosterjs/blob/2e598554cbd848ebb1fcd823656f7aa4d0aa47b2/packages-ui/roosterjs-react/lib/rooster/component/Rooster.tsx#L23 is the place where we initialize this property. We assume that when use plugins under roosterjs-react package, the editor should also be initialized from `<Rooster />` component. If it is not the case, you need to create and initialize uiUtilities by yourself. but I agree we need to improve the error message to make this looks more clear. Let's use this issue to track error message improvement.

**Comment by BDMChau** [comment]
Thank you for supporting, I read the source code from v8.14 and saw the old demo code, so I knew how to create custom plugin for these. I also agree with you about improving the document between rooster from the core package and Rooster component from roosterjs-react, it confused me a bit
