### ISSUE TITLE
HtmlSanitizer.convertInlineCss not correctly handling pseudo-classes

### ISSUE THREAD

**Issue by adrienWeiss** [microsoft/roosterjs#1330]
**Describe the bug**
HtmlSanitizer instance convertGlobalCssToInlineCss() does not seem to handle correctly pseudo-classes such as `:first-child` or `:not()` 
It will either completely ignore these selectors, or throw an error in some cases, for example when using multiple values `:not(.foo, .bar)` 

**To Reproduce**
1. Go to the RoosterJS demo
2. Use API Playground > HTML Sanitizer
3. Input this : 
```html
<style>
div:first-child { display: none; }
div:not(.foo) { background:red; }
div:not(.bar, .baz) { font-weight: bold; }
</style>
<div>not visible</div>
<div class="foo">bold</div>
<div class="bar">red</div>
<div class="baz">red</div>
```

4. Click "Inline CSS"
5. Observe "Result" and browser Console : 
```html
<div>not visible</div>
<div class="foo">bold</div>
<div class="bar">red</div>
<div class="baz">red</div>
```
```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': ' .baz)' is not a valid selector.
```

**Expected behavior**
All four divs should have the correct inline styles attributes.

**Device Information**
 - OS: [e.g. iOS] : macOS 12.6
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : 8.33.1

Thank you

edit : replaced with `convertGlobalCssToInlineCss` since `convertInlineCss` is actually deprecated but the problem is the same (and the demo uses `convertGlobalCssToInlineCss`)

**Comment by romanisa** [comment]
@adrienWeiss this is not on our team's plan right now, but we are open to contribution. Please feel free to send a PR and we will be happy to help review.

**Comment by gm-al** [comment]
The issue is caused by how the method `convertGlobalCssToInlineCss()` processes and splits CSS selectors, specifically with those involving pseudo-classes with multiple parameters like `:not(.bar, .baz).` The current approach to splitting these selectors on commas divides them into separate, incomplete selectors. When these selectors are split, the method treats them as separate selectors, which results in invalid CSS selectors when trying to query the DOM.

## The cause of the issue
https://github.com/microsoft/roosterjs/blob/430acd72e5e3f8387a164b7d7960161ec279102c/packages/roosterjs-editor-dom/lib/htmlSanitizer/HtmlSanitizer.ts#L154-L155

## Manifesting the issue
Here, the results of loggin the selector of `:not(.bar, .baz)` results into two parts: `div:not(.bar` and `.baz)`, leading to an invalid query when passed to `querySelectorAll`, causing the `Uncaught DOMException`.

## Solution
We can handle this by creating a regex to split the selectorText, and avoid splitting what's inside parentheses. And remove `selector.indexOf(':') >= 0` to allow filtering out selectors containing colons `(:)`.
