### ISSUE TITLE
Long content doesn't wrap in Firefox, bottom scroll bar displays

### ISSUE THREAD

**Issue by natalieethell** [microsoft/roosterjs#1454]
**Describe the bug**
Long content cannot automatically wrap on Firefox. Instead, a bottom scroll bar displays. This repros in the roosterjs playground as well and impacts the SharePoint product, which consumes roosterjs.

**To Reproduce**
1. Go to the RoosterJS playground
2. Input long content (with no spaces, oontent with spaces will wrap). For example, continue pasting "testtesttesttest" until it passes the right side of the editor.
3. Observe the scrollbar growing at the bottom of the page, with no newlines.

![RoosterJSFirefoxScrollbar](https://user-images.githubusercontent.com/14134000/205387846-189e3cf2-c348-46ca-a18a-a6d27cbb1a27.gif)

**Expected behavior**
The text wraps to a newline in Firefox, as it does in Edge. Here is a screen capture of it working in Edge:
![RoosterJsEdgeNoScrollbar](https://user-images.githubusercontent.com/14134000/205387945-990717fe-c4f7-47e7-aa8c-0b30df586b9e.gif)

**Screenshots**
Firefox (not working)
![image](https://user-images.githubusercontent.com/14134000/205387020-9d28bcec-d51a-49ff-b625-7d381a08ea3e.png)

**Device Information**
 - OS: Windows 11 Enterprise
 - Browser: Firefox 107.0.1 (64-bit)

**Additional context**

**Comment by JiuqingSong** [comment]
Actually, layout is not the responsibility of roosterjs. You can always override this behavior by adding css rule `word-wrap: break-word` to the roosterjs DIV. You can try here:

For pure roosterjs: https://codepen.io/jiuqingsong/pen/ZERVEyo
![image](https://user-images.githubusercontent.com/23065085/205552639-371ccbcc-827f-4a10-9906-a4256e441f1f.png)

For roosterjs-react: https://codepen.io/jiuqingsong/pen/WNyLNZO
![image](https://user-images.githubusercontent.com/23065085/205552686-76dcb3fa-6596-4f80-be17-7e0f72eba86b.png)


We don't add this style by default since
1. RoosterJs is an editor engine, but not UI library, so it doesn't handle layout.
2. RoosterJs-react actually doesn't add any layout related CSS rule so that you can fully customize it.
3. It can also be a valid scenario to allow the horizontal scrollbar. It is easier to hide it than add it back.

**Comment by natalieethell** [comment]
Thanks for the info @JiuqingSong ! Closing
