### ISSUE TITLE
editor.select(selectionPath) sets the cursor at wrong position if there is more than one text node

### ISSUE THREAD

**Issue by MelvilQ** [microsoft/roosterjs#1459]
**Describe the bug**
The `editor.select(selectionPath)`-method does not put the cursor at the correct place if the destination HTML node contains two text nodes instead of just one.

**To Reproduce**

index.html

```
<button>Take Focus</button>
<div id="editorDiv"></div>
<script src="dist/main.js"></script>
```

index.js

```
var roosterjs = require('roosterjs');
var editorDiv = document.getElementById('editorDiv');
var editor = roosterjs.createEditor(editorDiv);

var selectionPath = null;

editor.setContent('<div id="content"></div>');
var content = document.getElementById('content');

var span2 = document.createElement('span');
var span3 = document.createElement('span');
span3.appendChild(document.createTextNode('Hello '));
span3.appendChild(document.createTextNode('World'));
span2.appendChild(span3);
content.appendChild(span2);

editorDiv.onblur = save;
editorDiv.onfocus = restore;

function save() {
	selectionPath = editor.getSelectionPath();
	console.log(JSON.stringify(selectionPath));
}

function restore() {
	editor.select(selectionPath);
	const selectionPath2 = editor.getSelectionPath();
	console.log(JSON.stringify(selectionPath2));
}
```

Click right behind the word "World" to set the cursor at the end. Then click in on the "Take Focus"-Button and then press tab to move the focus back into the editor.

The cursor is positioned in front of the word "World".

**Expected behavior**
The cursor position after `editor.select(editor.getSelectionPath())` should not be different.

**Comment by JiuqingSong** [comment]
selection path is mostly used for restore selection on to a DOM tree that is generated from "innerHTML" directly, in that case, the "2 separate text nodes" case won't happen. And when create the selection path we do treat multiple adjacent text nodes as single one on purpose.

To solve the problem in your code, you can do either
1. use Range instead of selection path, since your DOM tree is not modified at all, once you take a selection Range, it is always valid. Or,
2. Call editorDiv.normalize() before restore selection, this will merge these adjacent nodes.
