### ISSUE TITLE
Recommended way to write plugin that transform certain text strings into entity fields on paste?

### ISSUE THREAD

**Issue by vikasra-seekout** [microsoft/roosterjs#1465]
**Describe the bug**
We've been trying to write a plugin that transforms part of the pasted content - substrings within "{{ }}" to non editable entities on content paste. While I can successfully hook into the beforeBaste and contentChanged events - it is unclear how to update the document fragment in beforePaste to create an entity in the final document model.

We have tried creating entity placeholders via createEntityPlaceholder and then appending the returns nodes to the document fragment, however they do not show up in the final content model.

The documentation around how to add entities during paste is unclear, would appreciate if someone could point us in the right direction. (insertEntity seems to be optimized for when content model already exists)

**To Reproduce**
Write a plugin which uses the PluginEventType.BeforePaste. Unable to update the fragment to create entities in the final content model.

**Comment by BryanValverdeU** [comment]
Hello @vikasra-seekout 

A way to do this could be:

1. On the BeforePasteEvent, you could add a class property to the element you would like to turn into an entity. (You will need to add the class name added to the event sanitizing option so it is not removed when pasting the content, you can add it by: event.sanitizingOption.additionalAllowedCssClasses.push(YOUR_CLASSNAME)).
2. Then in the ContentChanged Event and the source of the event is Paste (`evt.type == PluginEventType.ContentChanged && evt.changeSource == ChangeSource.Paste`), since the elements are already in the editor you can query the elements using the class added in the BeforePaste event: `editor.queryElement('.${YOUR_CLASSNAME}')` and use `InsertEntity` API from `rooster-editor-api` package to insert your readonly entity. You might need to do some selection changes before calling the insertEntity API. Then remove the classname after to avoid the element from being processed again.

**Comment by vikasra-seekout** [comment]
Thank you @BryanValverdeU - this helps a lot.
