### ISSUE TITLE
data-ogsc is removed on backspace

### ISSUE THREAD

**Issue by BryanValverdeU** [microsoft/roosterjs#1504]
**Describe the bug**
when backspacing at the start of a block, the data-ogsc is removed from the span.

**To Reproduce**
1. Toggle Dark Mode
1. Add a line of text
2. Press enter.
3. Add text in second line
4. Backspace at the start of the second line
5. Both lines get merged, and the data-ogsc of the second span is removed.

**Expected behavior**
Second Span should keep the data-ogsc

**Screenshots**
![image](https://user-images.githubusercontent.com/8291124/212201156-6076d763-ab33-4fee-9981-bab6fbd7f5af.png)

**Comment by JiuqingSong** [comment]
I'm considering this solution:
1. When in light mode: use regular color in CSS: 
```html
<span style="color: #123456>test</span>
```
2. When switch to dark mode, change the color value to be a CSS variable and a fallback light color combination:
```html
<span style="color: var(--darkColor_123456, #123456)">test</span>
```
Also add a global CSS variable to HTML editor DIV:
```html
<div style="--darkColor_123456: #654321">...</div>
```
(Here assume 654321 is the dark value of 123456)
3. When transform back to light color, or dispose editor, parse this color value and replace with its original light color, and remove those CSS variables from editor DIV.
4. Same light color can reuse same global CSS variable. We can keep a map to remember what color has been calculated, so no need to recalculate.
5. In for any reason we didn't do dark to light transform when retrieve content (get HTML content, copy/cut, drag and drop, ...), since in the target container there is no such global CSS variable, browser will fallback to the second parameter of var() function which is the correct light mode color.
