### ISSUE TITLE
RoosterJS does not convert the links to clickable if they are passed  to internal content as plain text

### ISSUE THREAD

**Issue by Shtoosha** [microsoft/roosterjs#1653]
**Describe the bug**

**To Reproduce**
1. Create roosterJS component and pass  " http://life.com and https://fb.com and www.bing.com  some links" as initialContent prop 

**Expected behavior**
Links should clickable 

**Screenshots**
![image](https://user-images.githubusercontent.com/53274526/226086474-0d0c937c-aa8f-4eef-a47c-c75fe3b8816b.png)

**Device Information**
 - OS: Edge, Chrome

**Additional context**

**Comment by JiuqingSong** [comment]
This is by design. We don't change initial content. If you need this functionality, you can write a plugin to do it.

**Comment by JiuqingSong** [comment]
Actually, as a common editor, this is a "must-NOT-do". Because we always have an assumption: when user didn't do anything to the content inside an editor, the editing content should not be changed, as if user has never opened the content in editor.

Consider this scenario, user loaded some content with some string that looks like a link, and the editor auto-link them. Then user just close the editor without changing anything. Should we save or not save the new content now?

- If we don't save it since user didn't change anything, it means the content is different with what user has seen: user saw there are some links, but actually in the saved content there are not.
- If we save it since the content is actually changed (by editor), that means user doesn't know the original content doesn't have such links. This can be a security issue because it exposed a fact that user has opened and saw the content, which can be considered as a privacy. User doesn't know this content is changed although user didn't change anything.

As you can see, none of them is a valid scenario. So the root cause is we changed the content without letting user know. So the best solution is, we don't change it.

Of cause, you may have a requirement to do so, that is fine. But it should be done only in your system, but not as a common behavior inside a common editor.
