### ISSUE TITLE
Making getTooltipCallback in HyperLink async

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#1697]
Hi folks,

We've been recently working on improving tooltips for links, like this:

![image](https://user-images.githubusercontent.com/6745066/229462077-f99c160d-b21f-43f9-a8ee-8c4a5d021af9.png)

It's exactly something HyperLink's getTooltipCallback would do, however, we are working on a native app, which has something to do with a platform WebView, like `WKWebView` on iOS and macOS, where JavaScript cannot get values from native in a sync way, i.e., web to native round trip has to be async.

If we just want the tooltip look like `prefix + href`, the current design still works, as prefix is a static string, it can be provided by the native client as a configuration, but it doesn't work if we would like to pass the href to native client and get a string as the return value, dynamically.

I'd like to ask if you're OK with changing `getTooltipCallback` to optionally async, returns a `string | Promise<string>`, so that native apps can leverage this better, I can make the change if so.

Thanks!

**Comment by JiuqingSong** [comment]
In general, event handler should not be async because browser does not await on it. But for your case, you don't really need browser await, so async call here should be fine. 

However, to keep consistent for all event handlers in roosterjs, we will keep it as a sync call.

To solve the problem you are seeing. you can create a sub class of Hyperlink plugin and override the onMouse function (it is already a protected method so you can easily override it without changing the base class) and await on your own callback. Be careful of the execution order since mouse out event can be triggered before the async call is done so in that case you don't need to add the tooltip any more.
