### ISSUE TITLE
Release fix in 8.40.3 tag

### ISSUE THREAD

**Issue by Guillaumez** [microsoft/roosterjs#1724]
Hello !
Would it be possible for you to release [this fix](https://github.com/microsoft/roosterjs/pull/1645) in a `8.40.3` tag please ?

Thx in advance.

**Comment by JiuqingSong** [comment]
Can you help me understand why not use the latest release (8.45.0) which already includes this fix?

**Comment by Guillaumez** [comment]
We've tested our build with `8.40.2` and it's quite stable for our use. It should avoid us redoing QA and meet potential regressions.

**Comment by JiuqingSong** [comment]
I see. So that means you don't have plan to keep upgrading versions of roosterjs recently but want to stick into a special one. In that case I suggest clone/fork the code into your project and then you can do whatever change you need. The downside is you will lose any feature update/bug fix from roosterjs official release but since you don't have plan to upgrade version, I think that would be ok to you.

**Comment by Guillaumez** [comment]
Ok, thx 👍
