### ISSUE TITLE
How to get content on change of content in editor and how to get ref of editor using newly Rooster Wrapper from rooster core

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/roosterjs#1754]
Need some way to get content on change of content in editor in react.

I have integrated editor in the following way by seeing demo code from your repository.
```
const initialState: BuildInPluginState = {
    pluginList: {
        contentEdit: true,
        hyperlink: true,
        paste: true,
        watermark: false,
        imageEdit: true,
        cutPasteListChain: true,
        tableCellSelection: true,
        tableResize: true,
        customReplace: true,
        listEditMenu: true,
        imageEditMenu: true,
        tableEditMenu: true,
        contextMenu: true,
        autoFormat: true,
        contentModelFormat: true,
        contentModelEdit: false,
    },
    contentEditFeatures: getDefaultContentEditFeatureSettings(),
    defaultFormat: {},
    linkTitle: 'Ctrl+Click to follow the link:' + UrlPlaceholder,
    watermarkText: 'Type content here ...',
    forcePreserveRatio: false,
    experimentalFeatures: [
        "ListItemAlignment",
        "DefaultFormatInSpan",
        "AutoFormatList",
        "VariableBasedDarkColor",
        "ReusableContentModel",
        "InlineEntityReadOnlyDelimiters",
    ],
    isRtl: false,
};

export const RoosterEditor = () => {
    const [state, setState] = useState({ initState: initialState, editorCreator: undefined,displayRibbon:false});
    const ribbonPlugin = useRef<RibbonPlugin>(createRibbonPlugin());
    const imageEdit = useRef<ImageEdit>(new ImageEdit({ preserveRatio: false }));
    const contentRef = useRef<string>("");
    const editorRef = useRef<ContentModelEditor>();
    const onUpdate = (content: string) => {
        contentRef.current = content
    }
    const updateContentPlugin = useRef<EditorPlugin>(createUpdateContentPlugin(UpdateMode.OnDispose, onUpdate));

    const allPlugins = useRef<EditorPlugin[]>([
        ribbonPlugin.current,
        createPasteOptionPlugin(),
        createEmojiPlugin(),
        updateContentPlugin.current,
        new ContentEdit(state.initState.contentEditFeatures),
        new TableResize(),
        new TableCellSelection(),
        new AutoFormat(),
        new CustomReplacePlugin(),
        createContextMenuPlugin(),
        createListEditMenuProvider(),
        imageEdit.current,
        createImageEditMenuProvider(imageEdit.current),
        createTableEditMenuProvider(),
        new CutPasteListChain(),
        new Paste(),
        new HyperLink()
    ])

    return <Stack verticalFill>
            <Ribbon plugin={ribbonPlugin.current} buttons={getButtons([...AllButtonKeys]) as RibbonButton<AllButtonStringKeys>[]} dir={state.initState.isRtl ? 'rtl' : 'ltr'} />
        <Rooster
            plugins={allPlugins.current}
            defaultFormat={state.initState.defaultFormat}
            editorCreator={state.editorCreator}
            dir={state.initState.isRtl ? 'rtl' : 'ltr'}
            initialContent={contentRef.current}
            experimentalFeatures={state.initState.experimentalFeatures as ExperimentalFeatures[]}
            trustedHTMLHandler={trustedHTMLHandler}
            
        />
       </Stack>
}

```

Onchange of content how can i get content and update in local state?

**Comment by JiuqingSong** [comment]
Change of content can be caused by user's editing behavior (key in, cut/paste, drag/drop, ...) or program.

For user's regular input behavior (key in, delete, backspace, ...), it will trigger the following events:
- PluginEventType.KeyDown: Triggered when key down, before the change takes effect. This will be triggered for all keydown event, including those will not cause content change such as Up,Down
- PluginEventType.KeyPress: Similiar with KeyDown, but it will only be triggered by those key that will input something
- PluginEventType.Input: Triggered for all user's editing operation, happens after it takes effect

For content change caused by program, there should be a PluginEventType.ContentChanged event. Different kind of change action will take different parameter.

With the `<Rooster/>`  component, we don't support retrieving editor reference directly. But you can use the following way to get it:
- Use [editorCreator](https://github.com/microsoft/roosterjs/blob/78d871eebba05f01a16f021a4e66f2caaf7361f0/packages-ui/roosterjs-react/lib/rooster/type/RoosterProps.ts#L11) property. It allows you to create editor instance with your own code, So you an also store it somewhere when it is created.
- Create your own editor plugin. You will have access to editor instance inside a plugin

If you only want to access editor HTML content, you can use existing [plugin ](https://github.com/microsoft/roosterjs/blob/78d871eebba05f01a16f021a4e66f2caaf7361f0/packages-ui/roosterjs-react/lib/rooster/plugin/createUpdateContentPlugin.ts#L99), it let you provide a callback and it will be called per your requirement.

**Comment by JiuqingSong** [comment]
BTW, ContentModelEditor is still under development. We suggest to use the original Editor class for now.

For a simpler demo, you can go to https://microsoft.github.io/roosterjs/index.html#options and click "Try roosterjs-react in CodePen" from the right side.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/23065085/235584226-129a095d-e049-49f8-8516-85787ab731e6.png">

**Comment by bhanu345-cmd** [comment]
To have callback on change of content in editor, if we use createUpdateContentPlugin() what will be the mode to be passed to that plugin?

**Comment by JiuqingSong** [comment]
Please refer to https://microsoft.github.io/roosterjs/docs/enums/roosterjs_react.updatemode.html

It depends on your requirement. If you want to get it called every change that user made, you can pass OnUserInput and OnContentChangedEvent. If you want to get it called only when focus leaves editor, you can use OnBlur. If you want it only be called when you trigger it (by calling forceUpdate()), you can use Force.

**Comment by bhanu345-cmd** [comment]
useInput will not get triggered  when we do bold and underline changes right. If we want to get content on those changes as well how is it possible?

**Comment by JiuqingSong** [comment]
One single plugin can handle multiple events. It is up to you how many plugins you want to have. But logically the same purpose of code should be into the same plugin.
