### ISSUE TITLE
Difficulty in finding content change event (How to identify which event is getting trigged when we add something on editor)

### ISSUE THREAD

**Issue by SanjanaGodbole** [microsoft/roosterjs#1755]
<div className={styles.editorContainer}>
                <div style={editorStyles}>
                    <Rooster
                        className={styles.editor}
                        plugins={allPlugins}
                        defaultFormat={this.state.initState.defaultFormat}
                        inDarkMode={this.state.isDarkMode}
                        getDarkColor={getDarkColor}
                        experimentalFeatures={this.state.initState.experimentalFeatures}
                        undoMetadataSnapshotService={this.snapshotPlugin.getSnapshotService()}
                        trustedHTMLHandler={trustedHTMLHandler}
                        zoomScale={this.state.scale}
                        initialContent={this.content}
                        editorCreator={this.state.editorCreator}
                        dir={this.state.isRtl ? 'rtl' : 'ltr'}
                       />
                </div>
                <button onClick={this.OnclickEvt}> </button>
            </div>

  OnclickEvt = () => {
        let editorRefrence=document.getElementById('div') as HTMLDivElement;
        let editor = new ContentModelEditor(editorRefrence);
        console.log(editor.getContent());

    }

**Comment by JiuqingSong** [comment]
Change of content can be caused by user's editing behavior (key in, cut/paste, drag/drop, ...) or program.

For user's regular input behavior (key in, delete, backspace, ...), it will trigger the following events:
- PluginEventType.KeyDown: Triggered when key down, before the change takes effect. This will be triggered for all keydown event, including those will not cause content change such as Up,Down
- PluginEventType.KeyPress: Similiar with KeyDown, but it will only be triggered by those key that will input something
- PluginEventType.Input: Triggered for all user's editing operation, happens after it takes effect

For content change caused by program, there should be a PluginEventType.ContentChanged event. Different kind of change action will take different parameter.
