### ISSUE TITLE
Clicking on images brings different spacing

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#1816]
Please check out the video:

https://github.com/microsoft/roosterjs/assets/6745066/8448f984-7377-42f6-ace6-9d7fe8e50612

Is this UI glitch a known issue? Thanks.

**Comment by JiuqingSong** [comment]
At least for now, this is what we have and there is no plan to fix it.

If you have a solution, would you please submit a PR so that everyone can be benefited.

Thanks.

**Comment by JiuqingSong** [comment]
The change you mentioned is intentional since the original behavior has more problems.

I tried to change some CSS and it seems can be partially improved, at least before the image is rotated. Here is a draft, can you check and see if that is ok for you? https://github.com/microsoft/roosterjs/pull/1846
