### ISSUE TITLE
[Question] How can I use own class name?

### ISSUE THREAD

**Issue by bokuweb** [Microsoft/roosterjs#186]
Hi. I have some questions.
I would like to add my class name like following.

```
createEditorViewState(`<div class="MY_CLASS_NAME">Content</div>`)
```

This is because, I would like to use it to search element with `editor.queryElements`.
However this class is removed. (maybe, by html sanitizer?)
I tried to use custom tag (e.g `<MY_TAG>content</MY_TAG>`) but it is same result.

#### Questions
1. Can I add my class name to element in content?
2. If not, Is there a good way to find a specific DOM element?

thanks :)

**Comment by JiuqingSong** [comment]
Hi, I guess you are using the util function createEditorViewState() from roosterjs-react, is that right?

Yes, this function will do html sanitization for the content. If html sanitization is not require for you, or you'd like to customize how to sanitize, you can have your own implemetation of createEditorViewState() since it is very straightforward:

export default function createEditorViewState(initialContent?: string): EditorViewState {
    return {
        content: sanitizeHtml(initialContent) || '',
        isDirty: false
    };
}

You can just remove sanitizeHtml() call here, or pass more parameters to allow preserving "class" attribute.

**Comment by bokuweb** [comment]
Thanks for your quick response.

> createEditorViewState() from roosterjs-react, is that right?

That's right.

> You can just remove sanitizeHtml() call here, or pass more parameters to allow preserving "class" attribute.

I see. Thanks :) I'll try it !!
