### ISSUE TITLE
Weird selection copy bug working with WordMail

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#2004]
**Describe the bug**

This is a bit hard to reproduce, we only noticed it in some emails (the content was copied from a WordMail draft and pasted into rooster). To mock the environment, insert HTML into the editor using web inspector:

```html
<div>
  <p>
    <o:p>
      <p></p>
    </o:p>
  </p>
  <div>Hello</div>
</div>
```

For example:

![image](https://github.com/microsoft/roosterjs/assets/6745066/425963d3-55df-4ab6-b85a-8ffc03771e41)

Now select the word and cmd-c to copy (I only tested Mac, not sure about Windows), the result is that nothing is copied.

Note that, sometimes the HTML gets normalized to:

<img width="315" alt="image" src="https://github.com/microsoft/roosterjs/assets/6745066/28a68afa-25bb-4adc-ba08-11ae4b4aee59">

In that case it cannot be reproduced.

I also tried leveraging `HtmlSanitizer` but doesn't work. Is there another way to normalize the content?

Thanks!

**Comment by JiuqingSong** [comment]
I tried on Safari 16.6 on Mac and Edge  115.0.1901.188 on Windows, none of them can repro.

Once I restore the snapshot, the HTML structure is already normalized:
![image](https://github.com/microsoft/roosterjs/assets/23065085/40f773a7-0d3d-441a-9da9-2914211cac32)

But if that happens, it is most likely caused by a P tag inside another P tag which is not per HTML standard.

I believe with Content Model editor this won't happen.
