### ISSUE TITLE
VueJS Ribbon

### ISSUE THREAD

**Issue by AlphaGeek** [Microsoft/roosterjs#202]
Is there a VueJS ribbon or a standard way to add toolbar(ribbon) buttons to the rooster editor without creating them yourself (e.g. is there a plugin pre-built that will add the toolbar buttons)?

**Comment by JiuqingSong** [comment]
Unfortunately, we don't have existing implementation of ribbon for VueJs now. This is because roosterjs is designed as a framework-independent editor so it doesn't provide UI component by default. But you are very welcome to build your implementation and even contribute back as a new repo (say roosterjs-vue?)

**Comment by AlphaGeek** [comment]
Thanks for the reply.   Is there an example of how to add a standard formatting toolbar to the editor (perhaps via a plugin)?
