### ISSUE TITLE
`pre` tag does not support customized processor on Conten Model editor and `pre` tag should be processed as `Paragraph` instead of  `BlockGroup`

### ISSUE THREAD

**Issue by pmstar** [microsoft/roosterjs#2048]
**`pre` tag does not support customized processor on Conten Model editor and `pre` tag should be processed as `Paragraph` instead of  `BlockGroup`**
According to the roosterjs default processors, the `pre` tag will be processed by `formatContainerProcessor` functin, which will cause that `div` and `span` tags are added between `pre` and `code` tags. We should change the processor or support customized processor to fix this.

![image](https://github.com/microsoft/roosterjs/assets/8992966/fbaddda4-1e0d-4a94-8afd-04b241917faa)

**To Reproduce**
1. Copy fenced code block in the url: https://markdown.com.cn/extended-syntax/fenced-code-blocks.html;
2. Paste into the Content Model editor, url: https://microsoft.github.io/roosterjs/index.html?cm=1
![image](https://github.com/microsoft/roosterjs/assets/8992966/b70f8401-0bfc-4f2b-8d8c-78762a853273)
We can see that `div` and `span` tags are added between `pre` and `code` tags.

**Expected behavior**
When pasting HTML with fenced code block into editor, there is no any other tag between `pre` and `code`.

**Comment by JiuqingSong** [comment]
Thanks for reporting.

We tried several different ways to handle PRE tag before, but they all have some kind of problem that can cause the result is unexpected. So we finally decided to use Format Container to represnt PRE and at least its layout and behavior is as expected.

The fact is that it is possible there can be multiple DIV or even other tags inside PRE, so that we cannot represent PRE as a single Paragraph, but treat it as a container.

However, all element processors can be override, you can create your own processor to override the default one by passing it into `ContentModelEditorOptions.defaultDomToModelOptions.processorOverride`
