### ISSUE TITLE
Inserting Image Lags Typing

### ISSUE THREAD

**Issue by CMTietgen** [Microsoft/roosterjs#206]
**Describe the bug**
I insert an image, both via the Insert Image toolbar and copy/paste and once I do this, typing lags pretty bad. Up to 5 seconds, if not more. In fact, most UI interactions lag.

**To Reproduce**
1. Insert an image
2. Type in the editor

**Expected behavior**
There should be no lag.

**Device Information**
 - OS: Windows 10 x64; 1803.17134.523
 - Browser: Chrome 71.0.3578.98 x64
 - Version: 7.0.2

**Comment by JiuqingSong** [comment]
If you see this happens in the demo site with side bar opened, please try to close the side bar and see if this still happen.

Because the side bar has some code to show current HTML snapshot. Once inline image is inserted, the snapshot will be a huge string which causs large delay when render it.

Demo site (and its side bar) is just used for demo features and they are not part of production. So if this happens in demo site only, this is not a production bug. Instead, we will fix the demo site only.

**Comment by CMTietgen** [comment]
Sorry, I must have had the side bar open, as you said. I was unable to repro the issue with it closed.
