### ISSUE TITLE
Incorrect margin value applied to DOM element during modelToDOM transition

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#2222]
**Describe the bug**
I created a paragraph block with `<p>` decorator and inserted it into the editor by `mergeModel()`. I didn't specify any margin property for the block:

<img width="289" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/1c290a77-644c-4807-b016-e9d39040a1a5">

But when checking the inserted DOM element, I can see 2 margin properties on it, which is unexpected. 

<img width="585" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/12b8e22a-74ac-4005-bb09-ee389202ce58">

After some investigation, I found these margin properties were added by `marginFormatHandler`. Since the default format contains `marginTop` and `marginBottom`, and my element doesn't define them, the following `if` condition is met and `0` margin is applied to my element. 

<img width="571" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/8cabd0bf-dbdd-4fce-aad0-ef658696066f">

**To Reproduce**
1. Create a paragraph block with `<p>` decorator
2. Insert it into the editor
3. Check its margin

**Expected behavior**
If the margin is not specified, we shouldn't override it with `0px`.

**Comment by JiuqingSong** [comment]
This is by design. 
When margin is not specified, we treat it as 0. So if the tag implicitly has a margin, we will explicitly add margin:0 to override it.

To keep the default margin, you need to explicitly add some margin value to the model format.

Content Model is designed to show all format in the object in order to easily calculate, and all format API just need to directly read format and no need to consider what the tag is. If you convert a DOM tree with P tag into Content Model, it will automatically add the margins in format.
