### ISSUE TITLE
Touch: avoid use keypress event since it may not be supported in mobile

### ISSUE THREAD

**Issue by JiuqingSong** [Microsoft/roosterjs#241]
e.g., Chrome for android doesn't support onkeypress event: 
https://stackoverflow.com/questions/22473950/keypress-event-not-firing-in-android-mobile

We are using KeyPress event in several places, we should remove them:

- TypeInContainerPlugin
- Undo
- PickerPlugin

**Comment by tito0224** [comment]
I'm also seeing this issue on mobile chrome with KeyDown events. The `.key` property on the event is always `Undefined`. This prevents the PickerPlugin's onRemove callback from getting called since it can't detect the backspace key.

This is an interesting article I found while investigating this issue. https://medium.com/square-corner-blog/understanding-composition-browser-events-f402a8ed5643

Maybe we should consider using the `CompositionStart`, `CompositionUpdated` and `CompositionEnded` events?

**Comment by JiuqingSong** [comment]
@tito0224 do you know if keydown event.which works in mobile?

**Comment by JiuqingSong** [comment]
Fixed in #274
