### ISSUE TITLE
Minimal example for React+TypeScript in a SPA, preferably with FluentUI v9 theming

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/roosterjs#2618]
**Describe the bug**
The documentation does not provide any guidance on how to use React to actually use RoosterJS. Ideally, there would be a minimal example that shows the steps needed to add RoosterJS to a React app along with Fluent UI v9 (React) and a `<FluentProvider>`, set the contents from React State (`useState`), and update React State when the contents change (i.e., as the user types).

That's it. It feels like a really simple thing that anyone trying to use this library would want to know. I hate to submit question-like bugs, but I've now spent almost an hour digging through docs, Stack Overflow, Codepen examples, etc. and found nothing.

**Comment by JiuqingSong** [comment]
Hi, do you want to make a contribution with a demo?

Thanks.

**Comment by LarsKemmann** [comment]
No, the problem is I have no idea how on Earth to do what I'm asking you to document. 😂

~Lars
________________________________

**Comment by JiuqingSong** [comment]
Actually, I have no idea either. I have never used FluentUI v9 before. But roosterjs is designed to be framework-independent, it is just a pure javascript library without any dependency to any other framework, which means it should be able to work together with any framework. We focus on the editor engine itself, but not the UI component. Anyone who have interest can develop their own UI wrapper of roosterjs. We have a roosterjs-react library just because we need a demo site to show how roosterjs works and we also use it as a test platform. But it doesn't mean roosterjs-react is the main output, it is actually just a demo.

**Comment by LarsKemmann** [comment]
Ah, well that's helpful to know. Thank you. I might end up contributing an example, no promises though. 😅

**Comment by pradeept95** [comment]
FYI: @JiuqingSong

**Comment by JiuqingSong** [comment]
Thanks @pradeept95
