### ISSUE TITLE
Some links are pasted as <a> tag even when `autoLink = false` for AutoFormatPlugin

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2623]
**Describe the bug**
It looks like some links are pasted as a tag and not as a simple text (span or div tag) even when`autoLink = false` for `AutoFormatPlugin` 

**To Reproduce**
1. Open RoosterJS Demo website
2. Set autoLink option to false for AutoFormatPlugin
3. Copy url of the demo website
4. Paste url in the editor

**Expected behavior**
The link should be pasted as a simple text and not as a hyperlink tag when 

**Screenshots**

https://github.com/microsoft/roosterjs/assets/98852890/9e774079-e7bb-4406-bd40-e067f3c55e9f

**Device Information**
 - OS: MacOS
 - Browser: Edge
 - Version: RoosterJs 9.2.0

**Additional context**

**Comment by JiuqingSong** [comment]
This is by design. It is just Edge's copy behavior. When you copy the url from Edge, Edge will copy a hyperlink:

![image](https://github.com/microsoft/roosterjs/assets/23065085/2746c0df-260a-4ef0-b42c-9b72d6f832b4)


So when you paste, it will paste as link, since it was already link.

If you try in Chrome, you will see it won't paste as link.

**Comment by JiuqingSong** [comment]
Do you expect to remove hyperlink when paste if there is already link in clipboard? If so, you can create a plugin to remove it.
