### ISSUE TITLE
How to have a functionality to mention users in rooster

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/roosterjs#2663]
**Describe the bug**
How to have a functionality to mention users in rooster

**Comment by JiuqingSong** [comment]
There is no full functionality provided for mention since the feature heavily rely on your data and server side as well.

But we have a PickerPlugin to provide lower level support for a picker, such as triggering a picker, and moving selection in a picker. You still need to handle how to draw a picker (since it will have dependency to the UI framework you are using) and how to submit the selection. You can type "@" in demo site to see an example:

![image](https://github.com/microsoft/roosterjs/assets/23065085/b8d1b0ba-651d-494e-b981-e2cade5ac47d)

And here is the source code of this sample picker: https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controlsV2/plugins/SamplePickerPlugin.tsx
