### ISSUE TITLE
Unable to differentiate the selected state of the formatting options inside ribbon in High Contrast ‘Aquatic’ and ‘Desert’ mode in Windows

### ISSUE THREAD

**Issue by sonyshubham** [microsoft/roosterjs#2775]
**Describe the bug**
Unable to differentiate the selected state of the formatting options and update button in High Contrast ‘Aquatic’ and ‘Desert’ mode.

**To Reproduce**
1. Go to rooster dummy site
2. Click on bold and italic options
3. Enable high contrast theme and see that enabled outline is not visible

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/e3b78fe6-d19f-4470-a0d9-a0f292ad074b)
![image](https://github.com/user-attachments/assets/bfc52f84-8ea6-4888-a12d-38cd2753088b)

**Device Information**
 - OS:Windows 11
 - Browser Chrome

**Comment by JiuqingSong** [comment]
Hi, roosterjs demo site is just a demo. It is not supposed to be used as production code. 
And according to https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-react/README.md, please also do not use `roosterjs-react` in production code if you see any issue with it (such as this one) since it is just a demo.
