### ISSUE TITLE
Allow setBackgroundColor to not lose selection

### ISSUE THREAD

**Issue by adrienWeiss** [microsoft/roosterjs#2914]
Hello,

we're still in the process of migrating to contentModel API and we've found a behavior difference that affects the user experience.

What I'm describing is still observable on the current demo (9.16.0)

Applying `setBackgroundColor` now loses the selection, whereas `setTextColor` does not. Perhaps this is intended, as it allows the user to directly see the background color applied without having the selection overlay over it, but when users intend to apply both in that order, it looks like a bug. Could the selection loss be an option of setBackgroundColor ?
I tried to find a workaround by trying to save / restore the selection range but I still haven't found out how in contentModel API.

Cheers

**Comment by JiuqingSong** [comment]
Hi, all roosterjs format API are supposed to be replaceable, which means you can always create your own format API to replace the default one. So you can create your own setBackgroundColor API by copying code from the existing one and remove the code to change selection.

It is by design to unselect text after changing background color since user need to see the color after setting it. Keeping selection makes the color can't bee seen. Word has the same behavior. But if user doesn't like it, you can have your own implementation.
