### ISSUE TITLE
Picker Plugin prevents default behavior for hitting enter

### ISSUE THREAD

**Issue by leong1016** [microsoft/roosterjs#484]
**Describe the bug**
Picker Plugin prevents default behavior for hitting enter. When callout panel shows no results, the user still cannot hit enter to break the line.

**To Reproduce**
Steps to reproduce the behavior (in OWA) :
1. Trigger the picker plugin using '@', ':', or '/',
2. Hitting enter when there are results found inserts the first entity (depending on the feature),
3. Hitting enter when there are no results found has no reactions.

**Expected behavior**
When there are results found, it is a convenient way for the users to hit enter to accept the first suggestion. But when there are no results found, it would be great if we can recover the behavior of enter. Providing a method to let features to make their own decisions seems to be a solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/31297850/96818107-add03f80-13d5-11eb-91de-f77ad065fb6b.png)

**Comment by KAnder425** [comment]
The Rooster API has an existing mechanism for this scenario. In the onInitialize method of the PickerDataProvider interface, there is a callback method called setIsSuggestingCallback. This callback is provided by the picker plugin so that the PickerDataProvider can set the 'isSuggesting' value in the Plugin to false, which hides the Picker.

I will update the Rooster docs to clarify this.

I will also follow up on the change needed in the appropriate OWA data providers.

**Comment by KAnder425** [comment]
This has been fixed in the appropriate OWA data providers.
