### ISSUE TITLE
`insertContent` doesn't trigger `ContentChanged` event

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#499]
**Describe the bug**
When I called `RoosterEditor.insertContent`, the plugin event `ContentChanged` wasn't triggered

**To Reproduce**
1. Call `RoosterEditor.insertContent()` and observe the pluginEvent `ContentChanged`

**Device Information**
 - Version [7.16.0]

**Additional context**
I'm not sure if this is as expected

**Comment by JiuqingSong** [comment]
that is expected.

insertContent() can be a step of a larger change, or we can say, it is possible that one change contains multiple calls to insertContent(), so that we will let the caller decide when to trigger the ContentChanged event by calling editor.triggerContentChangedEvent(). Otherwise there might be too many events to trigger.
