### ISSUE TITLE
Set InitialContent with `\r\n`, `\r`, `\n`

### ISSUE THREAD

**Issue by Yat3s** [microsoft/roosterjs#534]
**Describe the bug**
The editor‘s height is 0 if the` initialcontent` is '\r\n'

**To Reproduce**
1. Create a `RoosterEditor` with '\r\n' initialcontent

**Expected behavior**
The editor can be input with a default height

**Screenshots**
![image](https://user-images.githubusercontent.com/14801837/115507736-1332b980-a2af-11eb-919e-2250252f1d58.png)

**Device Information**
 - OS: Android 11
 - Browser: Android WebView
 - Version: Chromium 88

**Comment by JiuqingSong** [comment]
This is expected behavior.
The initial content must be meaningful HTML. If you want the initial content to be an empty link, you can use `<div><br></div>`. "\r" or "\n" mean nothing in HTML.
If you want the initial content to be empty, but want the editor to have a minimum height, use CSS min-height for the content DIV. Roosterjs doesn't handle layout.
