### ISSUE TITLE
Rich text control: Underline is in black despite font color being green

### ISSUE THREAD

**Issue by jesomekh** [Microsoft/roosterjs#70]
![image](https://user-images.githubusercontent.com/31226374/41370847-95115e36-6efd-11e8-9ec5-2ef0c81e3045.png)

if you highlight the word, then change the font color again, then it will change to the correct color.

**Comment by JiuqingSong** [comment]
Can you provide a repro step?

Thanks.

**Comment by jesomekh** [comment]
Essentially, if you change the font color of a piece of text which is underlined, then the font color of the text will change BUT the underline color will not change (as pictured). You see in the screenshot the text is green but the underline is black. Once you highlight the text again and change the color, then the underline will swap to the new font color.

**Comment by JiuqingSong** [comment]
Will be fixed in 6.13.2

**Comment by Adjective-Object** [comment]
Afaict this has to do with the order of the <u> and <span style="rgb()..."> elements

If the underline is a parent of the style, it will be the parent text colour (in this case black)
if the underline is a child of the style, it will be the child text colour (in this case green).

Possible fixes as I see it
- Introduce ul normalization (e.g. if a ul has only one child, switch their orders so the child is the parent  of the ul
- when setting ul on an element, if the selected text is an entire inline element, make the ul a child of the inline element instead of a parent.

Thoughts @JiuqingSong ?
