### ISSUE TITLE
Unable to override default text color in editor

### ISSUE THREAD

**Issue by natalieethell** [microsoft/roosterjs#731]
We have a scenario where we would like to inherit the text color of an element outside of our editor. However, it seems like the Rooster editor always defaults color to #000000, as seen here: https://github.com/microsoft/roosterjs/blob/bc2dbaf1760e5f3f52a17015ae086d312bac7b2c/packages/roosterjs/lib/createEditor.ts.

```
let options: EditorOptions = {
        plugins: plugins,
        initialContent: initialContent,
        getDarkColor: getDarkColor,
        defaultFormat: {
            fontFamily: 'Calibri,Arial,Helvetica,sans-serif',
            fontSize: '11pt',
            textColor: '#000000',
        },
    };
```

So this will always override whatever other color we would want with "inherit". 

This is an issue for us when we have a dark theme. We're able to change the color to white when editing the content in dark mode, but we have an issue with the text after it's saved.

In SharePoint, we can change the theme of our site from dark -> light. If we have existing content that we created when in light mode, this text will be black. When we move over to a dark theme, this content will stay black. This is why we would like the ability to just inherit color from an outer element so that the text is readable.

Is it possible to override that color? Could we add the ability to pass in a default color, just like we're able to pass in initialContent as a prop? Thanks!

**Comment by JiuqingSong** [comment]
Can you try something like

        defaultFormat: {
            fontFamily: 'Calibri,Arial,Helvetica,sans-serif',
            fontSize: '11pt',
            textColor: 'inherit',
        },

________________________________
From: Natalie Ethell ***@***.***>
Sent: Thursday, January 27, 2022 11:45
To: microsoft/roosterjs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/roosterjs] Unable to override default text color in editor (Issue #731)


We have a scenario where we would like to inherit the text color of an element outside of our editor. However, it seems like the Rooster editor always defaults color to #000000, as seen here: https://github.com/microsoft/roosterjs/blob/bc2dbaf1760e5f3f52a17015ae086d312bac7b2c/packages/roosterjs/lib/createEditor.ts<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Froosterjs%2Fblob%2Fbc2dbaf1760e5f3f52a17015ae086d312bac7b2c%2Fpackages%2Froosterjs%2Flib%2FcreateEditor.ts&data=04%7C01%7Cjisong%40microsoft.com%7C121f65fe6a8746016c9708d9e1cd9715%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637789095408474551%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b7wmLPixM25GKUlmcqo%2BjJFcTg1U5dvmfRVrzPOWxkg%3D&reserved=0>.

let options: EditorOptions = {
        plugins: plugins,
        initialContent: initialContent,
        getDarkColor: getDarkColor,
        defaultFormat: {
            fontFamily: 'Calibri,Arial,Helvetica,sans-serif',
            fontSize: '11pt',
            textColor: '#000000',
        },
    };


So this will always override whatever other color we would want with "inherit".

This is an issue for us when we have a dark theme. We're able to change the color to white when editing the content in dark mode, but we have an issue with the text after it's saved.

In SharePoint, we can change the theme of our site from dark -> light. If we have existing content that we created when in light mode, this text will be black. When we move over to a dark theme, this content will stay black. This is why we would like the ability to just inherit color from an outer element so that the text is readable.

Is it possible to override that color? Could we add the ability to pass in a default color, just like we're able to pass in initialContent as a prop? Thanks!

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Froosterjs%2Fissues%2F731&data=04%7C01%7Cjisong%40microsoft.com%7C121f65fe6a8746016c9708d9e1cd9715%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637789095408474551%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LCXMOcM%2B6k1OHQCuFEvsJjJVww%2FfWyuIWeKiGL6wLoM%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFP7D7MWMJTIYNM3N75VOQTUYGOGBANCNFSM5M64A2SQ&data=04%7C01%7Cjisong%40microsoft.com%7C121f65fe6a8746016c9708d9e1cd9715%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637789095408524528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FwQsufmcWlqbW9H1koFICQG3A9hVzxi3A8WCbsdvoCo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjisong%40microsoft.com%7C121f65fe6a8746016c9708d9e1cd9715%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637789095408524528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NNw2WmYGj9TG4pbJ0jpUXrnN7jHFbKXOL0iNyEnNLHY%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjisong%40microsoft.com%7C121f65fe6a8746016c9708d9e1cd9715%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637789095408524528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5POl9WBGb6bJqWZilVvGamf1HFT2ZYUcdTb24sOQV8U%3D&reserved=0>.

**Comment by natalieethell** [comment]
In a PR to change the Rooster code? Or in my app's code? (If the latter, where would we pass this in?)

**Comment by JiuqingSong** [comment]
In your app.

that should be in the place where you create editor. can you show me the code how you create editor?
________________________________

**Comment by natalieethell** [comment]
I might be missing something, but in the `createEditor` code it looks like there's no way to pass in additional options, though, right? Since the only params are `contentDiv`, `additionalPlugins`, and `initialContent`.

```
export default function createEditor(
    contentDiv: HTMLDivElement,
    additionalPlugins?: EditorPlugin[],
    initialContent?: string
): IEditor {
    let plugins: EditorPlugin[] = [new HyperLink(), new Paste(), new ContentEdit()];

    if (additionalPlugins) {
        plugins = plugins.concat(additionalPlugins);
    }

    let options: EditorOptions = {
        plugins: plugins,
        initialContent: initialContent,
        getDarkColor: getDarkColor,
        defaultFormat: {
            fontFamily: 'Calibri,Arial,Helvetica,sans-serif',
            fontSize: '11pt',
            textColor: '#000000',
        },
    };
    return new Editor(contentDiv, options);
}
```

This is how we create the editor:

```
const editor: Editor = createEditor(
        divElement,
        [this._enterPlugin, this._pastePlugin, this._commandBarPlugin],
        this.props.content
      );
```

**Comment by natalieethell** [comment]
Ah, I guess we could just create it using the new Editor constructor, is that what you're suggesting?

**Comment by JiuqingSong** [comment]
That is right
________________________________

**Comment by JiuqingSong** [comment]
Can I treat this one as closed? @natalieethell

**Comment by natalieethell** [comment]
Yes, thanks!
